theme: jekyll-theme-minimal
title: [Data-Centric Machine Learning Workshop @ Neurips 2021]
description: [A workshop covering all aspects of shaping the behavior of models by shaping their training data.]
